-- =====================================================================
-- Backfill de esquema: feriados_portugal, plantao_voluntarios, a view
-- feriados_sem_plantao, e 3 políticas RLS de escala_semanal
-- (escala_diaria_gerente_all, escala_diaria_operador_readonly,
-- escala_diaria_operador_select) existem em produção desde antes do
-- histórico de migrações (a 0008 já as pressupõe: "plantao_voluntarios
-- existe desde antes desta sessão, tal como feriados_portugal e a view
-- feriados_sem_plantao"), mas nenhuma migração alguma vez as criou —
-- reconstruir a base do zero falhava a meio. Achado do stress-test de
-- documentação (2026-09-28).
--
-- Esta migração é idempotente (IF NOT EXISTS / DROP+CREATE POLICY) e
-- reproduz exatamente a definição já em vigor em produção (confirmada
-- por introspecção direta ao catálogo antes de escrever este ficheiro)
-- — não muda nada onde os objetos já existem; só fecha a lacuna para
-- uma base nova.
-- =====================================================================

create table if not exists feriados_portugal (
    id bigint generated by default as identity primary key,
    data date not null,
    nome text not null,
    tipo text not null default 'NACIONAL',
    ano integer not null,
    descricao text,
    criado_em timestamptz not null default now(),
    constraint feriados_portugal_data_key unique (data)
);
create index if not exists idx_feriados_data on feriados_portugal (data);
create index if not exists idx_feriados_ano on feriados_portugal (ano);

alter table feriados_portugal enable row level security;

drop policy if exists feriados_portugal_select_all on feriados_portugal;
create policy feriados_portugal_select_all on feriados_portugal
    for select to authenticated using (true);


create table if not exists plantao_voluntarios (
    id bigint generated by default as identity primary key,
    data_feriado date not null,
    usuario_id uuid not null references usuarios(id),
    voluntario boolean not null default true,
    confirmado_em timestamptz,
    criado_em timestamptz not null default now(),
    confirmado_por uuid references usuarios(id),
    constraint plantao_voluntarios_data_feriado_usuario_id_key unique (data_feriado, usuario_id)
);
create index if not exists idx_plantao_data on plantao_voluntarios (data_feriado);
create index if not exists idx_plantao_usuario on plantao_voluntarios (usuario_id);
create index if not exists idx_plantao_voluntario on plantao_voluntarios (voluntario);
create unique index if not exists plantao_voluntarios_unico_confirmado
    on plantao_voluntarios (data_feriado) where (voluntario = true);

alter table plantao_voluntarios enable row level security;

drop policy if exists plantao_voluntarios_select_all on plantao_voluntarios;
create policy plantao_voluntarios_select_all on plantao_voluntarios
    for select to authenticated using (true);

drop policy if exists plantao_voluntarios_insert_gerente on plantao_voluntarios;
create policy plantao_voluntarios_insert_gerente on plantao_voluntarios
    for insert to authenticated with check (is_gerente_ou_delegado());

drop policy if exists plantao_voluntarios_update_titular on plantao_voluntarios;
create policy plantao_voluntarios_update_titular on plantao_voluntarios
    for update to authenticated using (is_gerente_titular()) with check (is_gerente_titular());

drop policy if exists plantao_voluntarios_delete_titular on plantao_voluntarios;
create policy plantao_voluntarios_delete_titular on plantao_voluntarios
    for delete to authenticated using (is_gerente_titular());


create or replace view feriados_sem_plantao
    with (security_invoker = true) as
select
    f.data,
    f.nome,
    f.tipo,
    (select count(*) from escala_semanal e join usuarios u on u.id = e.usuario_id
      where e.semana_ref = f.data and e.turno = 'H3' and u.ativo) as tem_h3,
    (select e.usuario_id from escala_semanal e join usuarios u on u.id = e.usuario_id
      where e.semana_ref = f.data and e.turno = 'H3' and u.ativo limit 1) as h3_usuario_id,
    (select count(*) from plantao_voluntarios p join usuarios u on u.id = p.usuario_id
      where p.data_feriado = f.data and p.voluntario = true and u.ativo) as voluntarios_confirmados,
    array_agg(distinct pv.usuario_id) filter (where pv.voluntario = true) as voluntarios_ids
from feriados_portugal f
left join (
    select p.id, p.data_feriado, p.usuario_id, p.voluntario, p.confirmado_em, p.criado_em, p.confirmado_por
    from plantao_voluntarios p join usuarios u on u.id = p.usuario_id and u.ativo
) pv on f.data = pv.data_feriado
where extract(year from f.data) = extract(year from current_date)
group by f.data, f.nome, f.tipo
having count(pv.usuario_id) filter (where pv.voluntario = true) = 0;


drop policy if exists escala_diaria_gerente_all on escala_semanal;
create policy escala_diaria_gerente_all on escala_semanal
    for all
    using (exists (select 1 from usuarios where usuarios.id = auth.uid() and usuarios.perfil = 'GERENTE' and usuarios.ativo = true))
    with check (exists (select 1 from usuarios where usuarios.id = auth.uid() and usuarios.perfil = 'GERENTE' and usuarios.ativo = true));

drop policy if exists escala_diaria_operador_readonly on escala_semanal;
create policy escala_diaria_operador_readonly on escala_semanal
    for select
    using (auth.uid() in (select usuarios.id from usuarios where usuarios.perfil = any (array['OPERADOR'::perfil_usuario, 'OPERADOR_H3'::perfil_usuario])));

drop policy if exists escala_diaria_operador_select on escala_semanal;
create policy escala_diaria_operador_select on escala_semanal
    for select
    using (auth.uid() = usuario_id or exists (select 1 from usuarios where usuarios.id = auth.uid() and usuarios.perfil = 'GERENTE'));
